### PR TITLE
Trying to test all of bmpts.m

### PR DESCRIPTION
**Pull request by jmlarson1**
@wildsm I'm trying to cover the branch of `bmpts.m` that is invoked when "Geometry points need to be coordinate directions!"

I'm trying to do so with pounders minimizing the 2-norm squared. I think having a small initial delta and points far outside of the TR would do so. I've tried different starting points near the origin, bounds, and other points in `X0` but it doesn't go down that branch of `bmpts`. 

Thoughts on adjusting this test file?

### CODE REVIEW

**Comment by wildsm** [comment]
I have updated the test to obtain the desired behavior. 
However, it has illuminated a bug with the current version of formquad whereby Hresdel is returned as empty:
```
Error using  + 
Arrays have incompatible sizes for this operation.

Error in pounders (line 187)
    Hres = Hres + Hresdel;

Error in test_bmpts (line 33)
[X, F, flag, xk_best] = pounders(objective, X0, n, npmax, nfmax, gtol, delta, nfs, m, F0, xkin, L, U, 0, 1);
```

I have moved this PR to draft while this is sorted out (I will look into it as well, but not immediately)

**Comment by jmlarson1** [comment]
As you may know, a basic debug of this new error: 
- The first call to `formquad` on line 159 exits noting `% Need to evaluate more points, then recall` with `Mdir == eye(2)`. I think this is desired.
- The call to `bmpts` adjusts `Mdir==(eye(2)-diag([1e-8,1e-8]))`. I think this is desired, since `X(xkin, :) == [1e-8, 1e-8]`.
- The second call to `formquad` on line 181 exits noting `% Need to evaluate more points, then recall` with `Mdir == eye(2)` and an empty `Hresdel`. I think this is incorrect.

**Comment by wildsm** [comment]
The modified code now throws an error to indicate that there are numerical issues and one cannot proceed with the current value of `Par`.

Note that for testing purposes one can see three different behaviors `test_bmpts.m`:

1.  `Par(3) = Par(4) = 1e-3;` (default): generates new set of `n` directions but then hits this error
2.  `Par(3) = 1e-4; Par(4) = 1e-3;` : no errors or warnings (easy validity)
3.  `Par(3) = 1e-3; Par(4) = 1e-4;` generates new set of `n` directions and can continue (but model never valid)

The long-term solution is to relax pivot values; I will put this in a separate commit for testing.

**Review by wildsm — APPROVED** [review]
This test now generates the desired coverage.
@jmlarson1 merge after you approve

**Pull request merged**
