### PR TITLE
Normalized python strings

### PR DESCRIPTION
**Pull request by jmlarson1**
Just removing the skip of string normalization from `.black`.

### CODE REVIEW

**Comment by jared321** [comment]
All of the changes look correct to me.  I didn't see any accidental typos associated with the changes.

I see that the main change is removing `skip-string-normalization = true` from the black configuration.  I also see that black was automatically run and succeeded.  If you still had single quote characters used in defining a string somewhere in the python code, would black or some other tool have complained now?

**Comment by jmlarson1** [comment]
@jared321 The great thing about black is that I just had to remove the `skip-string-normalization = true` line and run 
`black --config=.black .` and it will automatically make the changes.

And yes, the GitHub actions would complain if there were any single-quote characters defining a python string. (But it wouldn't complain, for example, about a single quote in string with a contraction such as `"Isn't black awesome"`.)

**Comment by jared321** [comment]
In other words, you have complete confirmation that the change was made successfully everywhere it was needed.  Sounds good!

One practice that I like is having the PR issuer state in the PR what steps they themselves have taken to ascertain that the changes are correct.  As an example, you could state upfront for this PR that passing automatic tests imply success.

**Review by jared321 — APPROVED** [review]

**Comment by jmlarson1** [comment]
> One practice that I like is having the PR issuer state in the PR what steps they themselves have taken to ascertain that the changes are correct. As an example, you could state upfront for this PR that passing automatic tests imply success.

I can state that going forward, but I hope that the fact that the "checks have passed" include `black` testing means it might not be needed. Same for "regression tests" if we can get them running on GitHub CI as well.

**Pull request merged**
