### PR TITLE
Scaling some goombah subproblems

### PR DESCRIPTION
**Pull request by jmlarson1**

### CODE REVIEW

**Review by mmenickelly — COMMENTED** [review]
Changes to scaling in goombah subproblems are fine, and apparently helpful on a carefully selected subset of test problems. 

What, though, is the reasoning for turning on the allow_recalc flag in manifold_sampling/m/call_user_scripts.m by default? Isn't this something we would want to explicitly flag and halt the solver?

**Comment by jmlarson1** [comment]
When running our 424 benchmark problems (53 problems, 4 h examples, constrained and unconstrained), there were a few instances where the same point was requested (at some point in the run). I believe this was more common with the constrained problems. 

Note that the code sometimes allows (or doesn't allow) recalc
`manifold_sampling/m/manifold_sampling_primal.m`,  
`goombah/m/goombah.m` (in two locations), and 
`goombah/m/goombah_wo_msp.m` 

all `allow_recalc`, but

`manifold_sampling/m/evaluate_points_to_force_valid_model.m` and
`manifold_sampling/m/update_models.m` 
do not.

Is this the correct convention (in your mind @mmenickelly )?

**Comment by mmenickelly** [comment]
OK, I went through the various choices of allow_recalc, and I can see why we should do this. 

It's completely reasonable (_especially_ on constrained problems) that two sequential subproblems might end up returning (nearly) the same point. But any attempt to correct a model obviously should not allow this to happen, or else the next pass of formquad will almost certainly just ignore the point you just tried to evaluate. 

I'm going to approve this PR now.

**Review by mmenickelly — APPROVED** [review]
Following prior comments, approved.

**Pull request merged**
